"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.  # noqa: E501

    The version of the OpenAPI document: 6.2.1
    Contact: dev@morpheusdata.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.billing_instance import BillingInstance
from openapi_client.model.get_billing_instances_identifier200_response_all_of import GetBillingInstancesIdentifier200ResponseAllOf
from openapi_client.model.model200_success import Model200Success
globals()['BillingInstance'] = BillingInstance
globals()['GetBillingInstancesIdentifier200ResponseAllOf'] = GetBillingInstancesIdentifier200ResponseAllOf
globals()['Model200Success'] = Model200Success
from openapi_client.model.get_billing_instances_identifier200_response import GetBillingInstancesIdentifier200Response


class TestGetBillingInstancesIdentifier200Response(unittest.TestCase):
    """GetBillingInstancesIdentifier200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBillingInstancesIdentifier200Response(self):
        """Test GetBillingInstancesIdentifier200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBillingInstancesIdentifier200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
