"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.  # noqa: E501

    The version of the OpenAPI document: 6.2.1
    Contact: dev@morpheusdata.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.policy_config_one_of15 import PolicyConfigOneOf15


class TestPolicyConfigOneOf15(unittest.TestCase):
    """PolicyConfigOneOf15 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyConfigOneOf15(self):
        """Test PolicyConfigOneOf15"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PolicyConfigOneOf15()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
