"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.  # noqa: E501

    The version of the OpenAPI document: 6.2.1
    Contact: dev@morpheusdata.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server import Server
globals()['Server'] = Server
from openapi_client.model.update_host_assign_tenant200_response_all_of import UpdateHostAssignTenant200ResponseAllOf


class TestUpdateHostAssignTenant200ResponseAllOf(unittest.TestCase):
    """UpdateHostAssignTenant200ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateHostAssignTenant200ResponseAllOf(self):
        """Test UpdateHostAssignTenant200ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateHostAssignTenant200ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
