"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.  # noqa: E501

    The version of the OpenAPI document: 6.2.1
    Contact: dev@morpheusdata.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.acknowledge_health_alarms_request_alarm import AcknowledgeHealthAlarmsRequestAlarm
globals()['AcknowledgeHealthAlarmsRequestAlarm'] = AcknowledgeHealthAlarmsRequestAlarm
from openapi_client.model.acknowledge_health_alarms_request import AcknowledgeHealthAlarmsRequest


class TestAcknowledgeHealthAlarmsRequest(unittest.TestCase):
    """AcknowledgeHealthAlarmsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcknowledgeHealthAlarmsRequest(self):
        """Test AcknowledgeHealthAlarmsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AcknowledgeHealthAlarmsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
