/**
 * Morpheus API
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: dev@morpheusdata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MorpheusApi);
  }
}(this, function(expect, MorpheusApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MorpheusApi.ArchiveFileLinks();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArchiveFileLinks', function() {
    it('should create an instance of ArchiveFileLinks', function() {
      // uncomment below and update the code to test ArchiveFileLinks
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be.a(MorpheusApi.ArchiveFileLinks);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property secretAccessKey (base name: "secretAccessKey")', function() {
      // uncomment below and update the code to test the property secretAccessKey
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property archiveFile (base name: "archiveFile")', function() {
      // uncomment below and update the code to test the property archiveFile
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "dateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "lastUpdated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property lastAccessDate (base name: "lastAccessDate")', function() {
      // uncomment below and update the code to test the property lastAccessDate
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property expirationDate (base name: "expirationDate")', function() {
      // uncomment below and update the code to test the property expirationDate
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

    it('should have the property downloadCount (base name: "downloadCount")', function() {
      // uncomment below and update the code to test the property downloadCount
      //var instance = new MorpheusApi.ArchiveFileLinks();
      //expect(instance).to.be();
    });

  });

}));
