/**
 * Morpheus API
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.2.1
 * Contact: dev@morpheusdata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MorpheusApi);
  }
}(this, function(expect, MorpheusApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MorpheusApi.StorageType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StorageType', function() {
    it('should create an instance of StorageType', function() {
      // uncomment below and update the code to test StorageType
      //var instane = new MorpheusApi.StorageType();
      //expect(instance).to.be.a(MorpheusApi.StorageType);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property displayOrder (base name: "displayOrder")', function() {
      // uncomment below and update the code to test the property displayOrder
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property defaultType (base name: "defaultType")', function() {
      // uncomment below and update the code to test the property defaultType
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property customLabel (base name: "customLabel")', function() {
      // uncomment below and update the code to test the property customLabel
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property customSize (base name: "customSize")', function() {
      // uncomment below and update the code to test the property customSize
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

    it('should have the property customSizeOptions (base name: "customSizeOptions")', function() {
      // uncomment below and update the code to test the property customSizeOptions
      //var instance = new MorpheusApi.StorageType();
      //expect(instance).to.be();
    });

  });

}));
