<?php
/**
 * Dashboard
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Morpheus API
 *
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.2.1
 * Contact: dev@morpheusdata.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Dashboard Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class Dashboard implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'dashboard';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'success' => 'bool',
        'instance_stats' => '\OpenAPI\Client\Model\DashboardInstanceStats',
        'provisioning' => '\OpenAPI\Client\Model\DashboardProvisioning',
        'monitoring' => '\OpenAPI\Client\Model\DashboardMonitoring',
        'backups' => '\OpenAPI\Client\Model\DashboardBackups',
        'activity' => '\OpenAPI\Client\Model\DashboardActivity[]',
        'log_stats' => '\OpenAPI\Client\Model\DashboardLogStats'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'success' => null,
        'instance_stats' => null,
        'provisioning' => null,
        'monitoring' => null,
        'backups' => null,
        'activity' => null,
        'log_stats' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'success' => 'success',
        'instance_stats' => 'instanceStats',
        'provisioning' => 'provisioning',
        'monitoring' => 'monitoring',
        'backups' => 'backups',
        'activity' => 'activity',
        'log_stats' => 'logStats'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'success' => 'setSuccess',
        'instance_stats' => 'setInstanceStats',
        'provisioning' => 'setProvisioning',
        'monitoring' => 'setMonitoring',
        'backups' => 'setBackups',
        'activity' => 'setActivity',
        'log_stats' => 'setLogStats'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'success' => 'getSuccess',
        'instance_stats' => 'getInstanceStats',
        'provisioning' => 'getProvisioning',
        'monitoring' => 'getMonitoring',
        'backups' => 'getBackups',
        'activity' => 'getActivity',
        'log_stats' => 'getLogStats'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['success'] = $data['success'] ?? null;
        $this->container['instance_stats'] = $data['instance_stats'] ?? null;
        $this->container['provisioning'] = $data['provisioning'] ?? null;
        $this->container['monitoring'] = $data['monitoring'] ?? null;
        $this->container['backups'] = $data['backups'] ?? null;
        $this->container['activity'] = $data['activity'] ?? null;
        $this->container['log_stats'] = $data['log_stats'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets success
     *
     * @return bool|null
     */
    public function getSuccess()
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     *
     * @param bool|null $success success
     *
     * @return self
     */
    public function setSuccess($success)
    {
        $this->container['success'] = $success;

        return $this;
    }

    /**
     * Gets instance_stats
     *
     * @return \OpenAPI\Client\Model\DashboardInstanceStats|null
     */
    public function getInstanceStats()
    {
        return $this->container['instance_stats'];
    }

    /**
     * Sets instance_stats
     *
     * @param \OpenAPI\Client\Model\DashboardInstanceStats|null $instance_stats instance_stats
     *
     * @return self
     */
    public function setInstanceStats($instance_stats)
    {
        $this->container['instance_stats'] = $instance_stats;

        return $this;
    }

    /**
     * Gets provisioning
     *
     * @return \OpenAPI\Client\Model\DashboardProvisioning|null
     */
    public function getProvisioning()
    {
        return $this->container['provisioning'];
    }

    /**
     * Sets provisioning
     *
     * @param \OpenAPI\Client\Model\DashboardProvisioning|null $provisioning provisioning
     *
     * @return self
     */
    public function setProvisioning($provisioning)
    {
        $this->container['provisioning'] = $provisioning;

        return $this;
    }

    /**
     * Gets monitoring
     *
     * @return \OpenAPI\Client\Model\DashboardMonitoring|null
     */
    public function getMonitoring()
    {
        return $this->container['monitoring'];
    }

    /**
     * Sets monitoring
     *
     * @param \OpenAPI\Client\Model\DashboardMonitoring|null $monitoring monitoring
     *
     * @return self
     */
    public function setMonitoring($monitoring)
    {
        $this->container['monitoring'] = $monitoring;

        return $this;
    }

    /**
     * Gets backups
     *
     * @return \OpenAPI\Client\Model\DashboardBackups|null
     */
    public function getBackups()
    {
        return $this->container['backups'];
    }

    /**
     * Sets backups
     *
     * @param \OpenAPI\Client\Model\DashboardBackups|null $backups backups
     *
     * @return self
     */
    public function setBackups($backups)
    {
        $this->container['backups'] = $backups;

        return $this;
    }

    /**
     * Gets activity
     *
     * @return \OpenAPI\Client\Model\DashboardActivity[]|null
     */
    public function getActivity()
    {
        return $this->container['activity'];
    }

    /**
     * Sets activity
     *
     * @param \OpenAPI\Client\Model\DashboardActivity[]|null $activity activity
     *
     * @return self
     */
    public function setActivity($activity)
    {
        $this->container['activity'] = $activity;

        return $this;
    }

    /**
     * Gets log_stats
     *
     * @return \OpenAPI\Client\Model\DashboardLogStats|null
     */
    public function getLogStats()
    {
        return $this->container['log_stats'];
    }

    /**
     * Sets log_stats
     *
     * @param \OpenAPI\Client\Model\DashboardLogStats|null $log_stats log_stats
     *
     * @return self
     */
    public function setLogStats($log_stats)
    {
        $this->container['log_stats'] = $log_stats;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


