/**
 * Morpheus API
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.2.1
 * Contact: dev@morpheusdata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RolePermissionTaskSetAll model module.
 * @module model/RolePermissionTaskSetAll
 * @version 6.2.1
 */
class RolePermissionTaskSetAll {
    /**
     * Constructs a new <code>RolePermissionTaskSetAll</code>.
     * @alias module:model/RolePermissionTaskSetAll
     * @param allTaskSets {Boolean} Apply to all workflows (taskSets)
     * @param access {module:model/RolePermissionTaskSetAll.AccessEnum} The new access level.
     */
    constructor(allTaskSets, access) { 
        
        RolePermissionTaskSetAll.initialize(this, allTaskSets, access);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, allTaskSets, access) { 
        obj['allTaskSets'] = allTaskSets;
        obj['access'] = access;
    }

    /**
     * Constructs a <code>RolePermissionTaskSetAll</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RolePermissionTaskSetAll} obj Optional instance to populate.
     * @return {module:model/RolePermissionTaskSetAll} The populated <code>RolePermissionTaskSetAll</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RolePermissionTaskSetAll();

            if (data.hasOwnProperty('allTaskSets')) {
                obj['allTaskSets'] = ApiClient.convertToType(data['allTaskSets'], 'Boolean');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Apply to all workflows (taskSets)
 * @member {Boolean} allTaskSets
 */
RolePermissionTaskSetAll.prototype['allTaskSets'] = undefined;

/**
 * The new access level.
 * @member {module:model/RolePermissionTaskSetAll.AccessEnum} access
 */
RolePermissionTaskSetAll.prototype['access'] = undefined;





/**
 * Allowed values for the <code>access</code> property.
 * @enum {String}
 * @readonly
 */
RolePermissionTaskSetAll['AccessEnum'] = {

    /**
     * value: "default"
     * @const
     */
    "default": "default",

    /**
     * value: "full"
     * @const
     */
    "full": "full",

    /**
     * value: "none"
     * @const
     */
    "none": "none"
};



export default RolePermissionTaskSetAll;

