/*
 * Morpheus API
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.2.1
 * Contact: dev@morpheusdata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiPowerSchedulesSchedule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-21T11:26:47.028Z[GMT]")
public class ApiPowerSchedulesSchedule {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  /**
   * Type of schedule &#x60;power&#x60; on or &#x60;power off&#x60;
   */
  @JsonAdapter(ScheduleTypeEnum.Adapter.class)
  public enum ScheduleTypeEnum {
    POWER("power"),
    
    POWER_OFF("power off");

    private String value;

    ScheduleTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ScheduleTypeEnum fromValue(String value) {
      for (ScheduleTypeEnum b : ScheduleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ScheduleTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ScheduleTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ScheduleTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ScheduleTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SCHEDULE_TYPE = "scheduleType";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_TYPE)
  private ScheduleTypeEnum scheduleType;

  public static final String SERIALIZED_NAME_SCHEDULE_TIMEZONE = "scheduleTimezone";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_TIMEZONE)
  private String scheduleTimezone = "UTC";

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled = true;

  public static final String SERIALIZED_NAME_MONDAY_ON_TIME = "mondayOnTime";
  @SerializedName(SERIALIZED_NAME_MONDAY_ON_TIME)
  private String mondayOnTime = "00:00";

  public static final String SERIALIZED_NAME_MONDAY_OFF_TIME = "mondayOffTime";
  @SerializedName(SERIALIZED_NAME_MONDAY_OFF_TIME)
  private String mondayOffTime = "24:00";

  public static final String SERIALIZED_NAME_TUESDAY_ON_TIME = "tuesdayOnTime";
  @SerializedName(SERIALIZED_NAME_TUESDAY_ON_TIME)
  private String tuesdayOnTime = "00:00";

  public static final String SERIALIZED_NAME_TUESDAY_OFF_TIME = "tuesdayOffTime";
  @SerializedName(SERIALIZED_NAME_TUESDAY_OFF_TIME)
  private String tuesdayOffTime = "24:00";

  public static final String SERIALIZED_NAME_WEDNESDAY_ON_TIME = "wednesdayOnTime";
  @SerializedName(SERIALIZED_NAME_WEDNESDAY_ON_TIME)
  private String wednesdayOnTime = "00:00";

  public static final String SERIALIZED_NAME_WEDNESDAY_OFF_TIME = "wednesdayOffTime";
  @SerializedName(SERIALIZED_NAME_WEDNESDAY_OFF_TIME)
  private String wednesdayOffTime = "24:00";

  public static final String SERIALIZED_NAME_THURSDAY_ON_TIME = "thursdayOnTime";
  @SerializedName(SERIALIZED_NAME_THURSDAY_ON_TIME)
  private String thursdayOnTime = "00:00";

  public static final String SERIALIZED_NAME_THURSDAY_OFF_TIME = "thursdayOffTime";
  @SerializedName(SERIALIZED_NAME_THURSDAY_OFF_TIME)
  private String thursdayOffTime = "24:00";

  public static final String SERIALIZED_NAME_FRIDAY_ON_TIME = "fridayOnTime";
  @SerializedName(SERIALIZED_NAME_FRIDAY_ON_TIME)
  private String fridayOnTime = "00:00";

  public static final String SERIALIZED_NAME_FRIDAY_OFF_TIME = "fridayOffTime";
  @SerializedName(SERIALIZED_NAME_FRIDAY_OFF_TIME)
  private String fridayOffTime = "24:00";

  public static final String SERIALIZED_NAME_SATURDAY_ON_TIME = "saturdayOnTime";
  @SerializedName(SERIALIZED_NAME_SATURDAY_ON_TIME)
  private String saturdayOnTime = "00:00";

  public static final String SERIALIZED_NAME_SATURDAY_OFF_TIME = "saturdayOffTime";
  @SerializedName(SERIALIZED_NAME_SATURDAY_OFF_TIME)
  private String saturdayOffTime = "24:00";

  public static final String SERIALIZED_NAME_SUNDAY_ON_TIME = "sundayOnTime";
  @SerializedName(SERIALIZED_NAME_SUNDAY_ON_TIME)
  private String sundayOnTime = "00:00";

  public static final String SERIALIZED_NAME_SUNDAY_OFF_TIME = "sundayOffTime";
  @SerializedName(SERIALIZED_NAME_SUNDAY_OFF_TIME)
  private String sundayOffTime = "24:00";


  public ApiPowerSchedulesSchedule name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * A name for the power schedule
   * @return name
  **/
  @ApiModelProperty(example = "Sample Threshold", required = true, value = "A name for the power schedule")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ApiPowerSchedulesSchedule description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A description for the power schedule
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A description for the power schedule")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ApiPowerSchedulesSchedule scheduleType(ScheduleTypeEnum scheduleType) {
    
    this.scheduleType = scheduleType;
    return this;
  }

   /**
   * Type of schedule &#x60;power&#x60; on or &#x60;power off&#x60;
   * @return scheduleType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of schedule `power` on or `power off`")

  public ScheduleTypeEnum getScheduleType() {
    return scheduleType;
  }


  public void setScheduleType(ScheduleTypeEnum scheduleType) {
    this.scheduleType = scheduleType;
  }


  public ApiPowerSchedulesSchedule scheduleTimezone(String scheduleTimezone) {
    
    this.scheduleTimezone = scheduleTimezone;
    return this;
  }

   /**
   * Time Zone eg. America/New_York, Europe/Amsterdam, etc.
   * @return scheduleTimezone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Time Zone eg. America/New_York, Europe/Amsterdam, etc.")

  public String getScheduleTimezone() {
    return scheduleTimezone;
  }


  public void setScheduleTimezone(String scheduleTimezone) {
    this.scheduleTimezone = scheduleTimezone;
  }


  public ApiPowerSchedulesSchedule enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Is the power schedule enabled
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Is the power schedule enabled")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public ApiPowerSchedulesSchedule mondayOnTime(String mondayOnTime) {
    
    this.mondayOnTime = mondayOnTime;
    return this;
  }

   /**
   * Monday Start time of the day in 24-hour format
   * @return mondayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Monday Start time of the day in 24-hour format")

  public String getMondayOnTime() {
    return mondayOnTime;
  }


  public void setMondayOnTime(String mondayOnTime) {
    this.mondayOnTime = mondayOnTime;
  }


  public ApiPowerSchedulesSchedule mondayOffTime(String mondayOffTime) {
    
    this.mondayOffTime = mondayOffTime;
    return this;
  }

   /**
   * Monday Off time of the day in 24-hour format
   * @return mondayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Monday Off time of the day in 24-hour format")

  public String getMondayOffTime() {
    return mondayOffTime;
  }


  public void setMondayOffTime(String mondayOffTime) {
    this.mondayOffTime = mondayOffTime;
  }


  public ApiPowerSchedulesSchedule tuesdayOnTime(String tuesdayOnTime) {
    
    this.tuesdayOnTime = tuesdayOnTime;
    return this;
  }

   /**
   * Tuesday Start time of the day in 24-hour format
   * @return tuesdayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Tuesday Start time of the day in 24-hour format")

  public String getTuesdayOnTime() {
    return tuesdayOnTime;
  }


  public void setTuesdayOnTime(String tuesdayOnTime) {
    this.tuesdayOnTime = tuesdayOnTime;
  }


  public ApiPowerSchedulesSchedule tuesdayOffTime(String tuesdayOffTime) {
    
    this.tuesdayOffTime = tuesdayOffTime;
    return this;
  }

   /**
   * Tuesday Off time of the day in 24-hour format
   * @return tuesdayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Tuesday Off time of the day in 24-hour format")

  public String getTuesdayOffTime() {
    return tuesdayOffTime;
  }


  public void setTuesdayOffTime(String tuesdayOffTime) {
    this.tuesdayOffTime = tuesdayOffTime;
  }


  public ApiPowerSchedulesSchedule wednesdayOnTime(String wednesdayOnTime) {
    
    this.wednesdayOnTime = wednesdayOnTime;
    return this;
  }

   /**
   * Wednesday Start time of the day in 24-hour format
   * @return wednesdayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Wednesday Start time of the day in 24-hour format")

  public String getWednesdayOnTime() {
    return wednesdayOnTime;
  }


  public void setWednesdayOnTime(String wednesdayOnTime) {
    this.wednesdayOnTime = wednesdayOnTime;
  }


  public ApiPowerSchedulesSchedule wednesdayOffTime(String wednesdayOffTime) {
    
    this.wednesdayOffTime = wednesdayOffTime;
    return this;
  }

   /**
   * Wednesday Off time of the day in 24-hour format
   * @return wednesdayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Wednesday Off time of the day in 24-hour format")

  public String getWednesdayOffTime() {
    return wednesdayOffTime;
  }


  public void setWednesdayOffTime(String wednesdayOffTime) {
    this.wednesdayOffTime = wednesdayOffTime;
  }


  public ApiPowerSchedulesSchedule thursdayOnTime(String thursdayOnTime) {
    
    this.thursdayOnTime = thursdayOnTime;
    return this;
  }

   /**
   * Thursday Start time of the day in 24-hour format
   * @return thursdayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Thursday Start time of the day in 24-hour format")

  public String getThursdayOnTime() {
    return thursdayOnTime;
  }


  public void setThursdayOnTime(String thursdayOnTime) {
    this.thursdayOnTime = thursdayOnTime;
  }


  public ApiPowerSchedulesSchedule thursdayOffTime(String thursdayOffTime) {
    
    this.thursdayOffTime = thursdayOffTime;
    return this;
  }

   /**
   * Thursday Off time of the day in 24-hour format
   * @return thursdayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Thursday Off time of the day in 24-hour format")

  public String getThursdayOffTime() {
    return thursdayOffTime;
  }


  public void setThursdayOffTime(String thursdayOffTime) {
    this.thursdayOffTime = thursdayOffTime;
  }


  public ApiPowerSchedulesSchedule fridayOnTime(String fridayOnTime) {
    
    this.fridayOnTime = fridayOnTime;
    return this;
  }

   /**
   * Friday Start time of the day in 24-hour format
   * @return fridayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Friday Start time of the day in 24-hour format")

  public String getFridayOnTime() {
    return fridayOnTime;
  }


  public void setFridayOnTime(String fridayOnTime) {
    this.fridayOnTime = fridayOnTime;
  }


  public ApiPowerSchedulesSchedule fridayOffTime(String fridayOffTime) {
    
    this.fridayOffTime = fridayOffTime;
    return this;
  }

   /**
   * Friday Off time of the day in 24-hour format
   * @return fridayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Friday Off time of the day in 24-hour format")

  public String getFridayOffTime() {
    return fridayOffTime;
  }


  public void setFridayOffTime(String fridayOffTime) {
    this.fridayOffTime = fridayOffTime;
  }


  public ApiPowerSchedulesSchedule saturdayOnTime(String saturdayOnTime) {
    
    this.saturdayOnTime = saturdayOnTime;
    return this;
  }

   /**
   * Saturday Start time of the day in 24-hour format
   * @return saturdayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Saturday Start time of the day in 24-hour format")

  public String getSaturdayOnTime() {
    return saturdayOnTime;
  }


  public void setSaturdayOnTime(String saturdayOnTime) {
    this.saturdayOnTime = saturdayOnTime;
  }


  public ApiPowerSchedulesSchedule saturdayOffTime(String saturdayOffTime) {
    
    this.saturdayOffTime = saturdayOffTime;
    return this;
  }

   /**
   * Saturday Off time of the day in 24-hour format
   * @return saturdayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Saturday Off time of the day in 24-hour format")

  public String getSaturdayOffTime() {
    return saturdayOffTime;
  }


  public void setSaturdayOffTime(String saturdayOffTime) {
    this.saturdayOffTime = saturdayOffTime;
  }


  public ApiPowerSchedulesSchedule sundayOnTime(String sundayOnTime) {
    
    this.sundayOnTime = sundayOnTime;
    return this;
  }

   /**
   * Sunday Start time of the day in 24-hour format
   * @return sundayOnTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sunday Start time of the day in 24-hour format")

  public String getSundayOnTime() {
    return sundayOnTime;
  }


  public void setSundayOnTime(String sundayOnTime) {
    this.sundayOnTime = sundayOnTime;
  }


  public ApiPowerSchedulesSchedule sundayOffTime(String sundayOffTime) {
    
    this.sundayOffTime = sundayOffTime;
    return this;
  }

   /**
   * Sunday Off time of the day in 24-hour format
   * @return sundayOffTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sunday Off time of the day in 24-hour format")

  public String getSundayOffTime() {
    return sundayOffTime;
  }


  public void setSundayOffTime(String sundayOffTime) {
    this.sundayOffTime = sundayOffTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiPowerSchedulesSchedule apiPowerSchedulesSchedule = (ApiPowerSchedulesSchedule) o;
    return Objects.equals(this.name, apiPowerSchedulesSchedule.name) &&
        Objects.equals(this.description, apiPowerSchedulesSchedule.description) &&
        Objects.equals(this.scheduleType, apiPowerSchedulesSchedule.scheduleType) &&
        Objects.equals(this.scheduleTimezone, apiPowerSchedulesSchedule.scheduleTimezone) &&
        Objects.equals(this.enabled, apiPowerSchedulesSchedule.enabled) &&
        Objects.equals(this.mondayOnTime, apiPowerSchedulesSchedule.mondayOnTime) &&
        Objects.equals(this.mondayOffTime, apiPowerSchedulesSchedule.mondayOffTime) &&
        Objects.equals(this.tuesdayOnTime, apiPowerSchedulesSchedule.tuesdayOnTime) &&
        Objects.equals(this.tuesdayOffTime, apiPowerSchedulesSchedule.tuesdayOffTime) &&
        Objects.equals(this.wednesdayOnTime, apiPowerSchedulesSchedule.wednesdayOnTime) &&
        Objects.equals(this.wednesdayOffTime, apiPowerSchedulesSchedule.wednesdayOffTime) &&
        Objects.equals(this.thursdayOnTime, apiPowerSchedulesSchedule.thursdayOnTime) &&
        Objects.equals(this.thursdayOffTime, apiPowerSchedulesSchedule.thursdayOffTime) &&
        Objects.equals(this.fridayOnTime, apiPowerSchedulesSchedule.fridayOnTime) &&
        Objects.equals(this.fridayOffTime, apiPowerSchedulesSchedule.fridayOffTime) &&
        Objects.equals(this.saturdayOnTime, apiPowerSchedulesSchedule.saturdayOnTime) &&
        Objects.equals(this.saturdayOffTime, apiPowerSchedulesSchedule.saturdayOffTime) &&
        Objects.equals(this.sundayOnTime, apiPowerSchedulesSchedule.sundayOnTime) &&
        Objects.equals(this.sundayOffTime, apiPowerSchedulesSchedule.sundayOffTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, scheduleType, scheduleTimezone, enabled, mondayOnTime, mondayOffTime, tuesdayOnTime, tuesdayOffTime, wednesdayOnTime, wednesdayOffTime, thursdayOnTime, thursdayOffTime, fridayOnTime, fridayOffTime, saturdayOnTime, saturdayOffTime, sundayOnTime, sundayOffTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiPowerSchedulesSchedule {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    scheduleType: ").append(toIndentedString(scheduleType)).append("\n");
    sb.append("    scheduleTimezone: ").append(toIndentedString(scheduleTimezone)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    mondayOnTime: ").append(toIndentedString(mondayOnTime)).append("\n");
    sb.append("    mondayOffTime: ").append(toIndentedString(mondayOffTime)).append("\n");
    sb.append("    tuesdayOnTime: ").append(toIndentedString(tuesdayOnTime)).append("\n");
    sb.append("    tuesdayOffTime: ").append(toIndentedString(tuesdayOffTime)).append("\n");
    sb.append("    wednesdayOnTime: ").append(toIndentedString(wednesdayOnTime)).append("\n");
    sb.append("    wednesdayOffTime: ").append(toIndentedString(wednesdayOffTime)).append("\n");
    sb.append("    thursdayOnTime: ").append(toIndentedString(thursdayOnTime)).append("\n");
    sb.append("    thursdayOffTime: ").append(toIndentedString(thursdayOffTime)).append("\n");
    sb.append("    fridayOnTime: ").append(toIndentedString(fridayOnTime)).append("\n");
    sb.append("    fridayOffTime: ").append(toIndentedString(fridayOffTime)).append("\n");
    sb.append("    saturdayOnTime: ").append(toIndentedString(saturdayOnTime)).append("\n");
    sb.append("    saturdayOffTime: ").append(toIndentedString(saturdayOffTime)).append("\n");
    sb.append("    sundayOnTime: ").append(toIndentedString(sundayOnTime)).append("\n");
    sb.append("    sundayOffTime: ").append(toIndentedString(sundayOffTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

