/*
 * Morpheus API
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.2.1
 * Contact: dev@morpheusdata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InlineResponse20040AppDeployInstance;
import org.openapitools.client.model.VirtualImageConfig;
import org.openapitools.client.model.VirtualImageOsType;
import org.threeten.bp.OffsetDateTime;

/**
 * VirtualImage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-21T11:26:47.028Z[GMT]")
public class VirtualImage {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private List<String> labels = null;

  public static final String SERIALIZED_NAME_OWNER_ID = "ownerId";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  private Long ownerId;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  private InlineResponse20040AppDeployInstance tenant;

  public static final String SERIALIZED_NAME_IMAGE_TYPE = "imageType";
  @SerializedName(SERIALIZED_NAME_IMAGE_TYPE)
  private String imageType;

  public static final String SERIALIZED_NAME_USER_UPLOADED = "userUploaded";
  @SerializedName(SERIALIZED_NAME_USER_UPLOADED)
  private Boolean userUploaded;

  public static final String SERIALIZED_NAME_USER_DEFINED = "userDefined";
  @SerializedName(SERIALIZED_NAME_USER_DEFINED)
  private Boolean userDefined;

  public static final String SERIALIZED_NAME_SYSTEM_IMAGE = "systemImage";
  @SerializedName(SERIALIZED_NAME_SYSTEM_IMAGE)
  private Boolean systemImage;

  public static final String SERIALIZED_NAME_IS_CLOUD_INIT = "isCloudInit";
  @SerializedName(SERIALIZED_NAME_IS_CLOUD_INIT)
  private Boolean isCloudInit;

  public static final String SERIALIZED_NAME_SSH_USERNAME = "sshUsername";
  @SerializedName(SERIALIZED_NAME_SSH_USERNAME)
  private String sshUsername;

  public static final String SERIALIZED_NAME_SSH_PASSWORD = "sshPassword";
  @SerializedName(SERIALIZED_NAME_SSH_PASSWORD)
  private String sshPassword;

  public static final String SERIALIZED_NAME_SSH_PASSWORD_HASH = "sshPasswordHash";
  @SerializedName(SERIALIZED_NAME_SSH_PASSWORD_HASH)
  private String sshPasswordHash;

  public static final String SERIALIZED_NAME_SSH_KEY = "sshKey";
  @SerializedName(SERIALIZED_NAME_SSH_KEY)
  private String sshKey;

  public static final String SERIALIZED_NAME_OS_TYPE = "osType";
  @SerializedName(SERIALIZED_NAME_OS_TYPE)
  private VirtualImageOsType osType;

  public static final String SERIALIZED_NAME_MIN_RAM = "minRam";
  @SerializedName(SERIALIZED_NAME_MIN_RAM)
  private Long minRam;

  public static final String SERIALIZED_NAME_MIN_RAM_G_B = "minRamGB";
  @SerializedName(SERIALIZED_NAME_MIN_RAM_G_B)
  private Long minRamGB;

  public static final String SERIALIZED_NAME_MIN_DISK = "minDisk";
  @SerializedName(SERIALIZED_NAME_MIN_DISK)
  private String minDisk;

  public static final String SERIALIZED_NAME_MIN_DISK_G_B = "minDiskGB";
  @SerializedName(SERIALIZED_NAME_MIN_DISK_G_B)
  private String minDiskGB;

  public static final String SERIALIZED_NAME_RAW_SIZE = "rawSize";
  @SerializedName(SERIALIZED_NAME_RAW_SIZE)
  private Long rawSize;

  public static final String SERIALIZED_NAME_RAW_SIZE_G_B = "rawSizeGB";
  @SerializedName(SERIALIZED_NAME_RAW_SIZE_G_B)
  private BigDecimal rawSizeGB;

  public static final String SERIALIZED_NAME_TRIAL_VERSION = "trialVersion";
  @SerializedName(SERIALIZED_NAME_TRIAL_VERSION)
  private Boolean trialVersion;

  public static final String SERIALIZED_NAME_VIRTIO_SUPPORTED = "virtioSupported";
  @SerializedName(SERIALIZED_NAME_VIRTIO_SUPPORTED)
  private Boolean virtioSupported;

  public static final String SERIALIZED_NAME_UEFI = "uefi";
  @SerializedName(SERIALIZED_NAME_UEFI)
  private String uefi;

  public static final String SERIALIZED_NAME_IS_AUTO_JOIN_DOMAIN = "isAutoJoinDomain";
  @SerializedName(SERIALIZED_NAME_IS_AUTO_JOIN_DOMAIN)
  private Boolean isAutoJoinDomain;

  public static final String SERIALIZED_NAME_VM_TOOLS_INSTALLED = "vmToolsInstalled";
  @SerializedName(SERIALIZED_NAME_VM_TOOLS_INSTALLED)
  private Boolean vmToolsInstalled;

  public static final String SERIALIZED_NAME_INSTALL_AGENT = "installAgent";
  @SerializedName(SERIALIZED_NAME_INSTALL_AGENT)
  private Boolean installAgent;

  public static final String SERIALIZED_NAME_IS_FORCE_CUSTOMIZATION = "isForceCustomization";
  @SerializedName(SERIALIZED_NAME_IS_FORCE_CUSTOMIZATION)
  private Boolean isForceCustomization;

  public static final String SERIALIZED_NAME_IS_SYSPREP = "isSysprep";
  @SerializedName(SERIALIZED_NAME_IS_SYSPREP)
  private Boolean isSysprep;

  public static final String SERIALIZED_NAME_FIPS_ENABLED = "fipsEnabled";
  @SerializedName(SERIALIZED_NAME_FIPS_ENABLED)
  private Boolean fipsEnabled;

  public static final String SERIALIZED_NAME_USER_DATA = "userData";
  @SerializedName(SERIALIZED_NAME_USER_DATA)
  private String userData;

  public static final String SERIALIZED_NAME_CONSOLE_KEYMAP = "consoleKeymap";
  @SerializedName(SERIALIZED_NAME_CONSOLE_KEYMAP)
  private String consoleKeymap;

  public static final String SERIALIZED_NAME_STORAGE_PROVIDER = "storageProvider";
  @SerializedName(SERIALIZED_NAME_STORAGE_PROVIDER)
  private String storageProvider;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  private String externalId;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private String visibility;

  public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS)
  private List<InlineResponse20040AppDeployInstance> accounts = null;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private VirtualImageConfig config;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private List<Object> volumes = null;

  public static final String SERIALIZED_NAME_STORAGE_CONTROLLERS = "storageControllers";
  @SerializedName(SERIALIZED_NAME_STORAGE_CONTROLLERS)
  private List<Object> storageControllers = null;

  public static final String SERIALIZED_NAME_NETWORK_INTERFACES = "networkInterfaces";
  @SerializedName(SERIALIZED_NAME_NETWORK_INTERFACES)
  private List<Object> networkInterfaces = null;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<Object> tags = null;

  public static final String SERIALIZED_NAME_LOCATIONS = "locations";
  @SerializedName(SERIALIZED_NAME_LOCATIONS)
  private List<Object> locations = null;

  public static final String SERIALIZED_NAME_DATE_CREATED = "dateCreated";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  private OffsetDateTime dateCreated;

  public static final String SERIALIZED_NAME_LAST_UPDATED = "lastUpdated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  private OffsetDateTime lastUpdated;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;


  public VirtualImage id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public VirtualImage name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VirtualImage description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public VirtualImage labels(List<String> labels) {
    
    this.labels = labels;
    return this;
  }

  public VirtualImage addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<String>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getLabels() {
    return labels;
  }


  public void setLabels(List<String> labels) {
    this.labels = labels;
  }


  public VirtualImage ownerId(Long ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(Long ownerId) {
    this.ownerId = ownerId;
  }


  public VirtualImage tenant(InlineResponse20040AppDeployInstance tenant) {
    
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InlineResponse20040AppDeployInstance getTenant() {
    return tenant;
  }


  public void setTenant(InlineResponse20040AppDeployInstance tenant) {
    this.tenant = tenant;
  }


  public VirtualImage imageType(String imageType) {
    
    this.imageType = imageType;
    return this;
  }

   /**
   * Get imageType
   * @return imageType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImageType() {
    return imageType;
  }


  public void setImageType(String imageType) {
    this.imageType = imageType;
  }


  public VirtualImage userUploaded(Boolean userUploaded) {
    
    this.userUploaded = userUploaded;
    return this;
  }

   /**
   * Get userUploaded
   * @return userUploaded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getUserUploaded() {
    return userUploaded;
  }


  public void setUserUploaded(Boolean userUploaded) {
    this.userUploaded = userUploaded;
  }


  public VirtualImage userDefined(Boolean userDefined) {
    
    this.userDefined = userDefined;
    return this;
  }

   /**
   * Get userDefined
   * @return userDefined
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getUserDefined() {
    return userDefined;
  }


  public void setUserDefined(Boolean userDefined) {
    this.userDefined = userDefined;
  }


  public VirtualImage systemImage(Boolean systemImage) {
    
    this.systemImage = systemImage;
    return this;
  }

   /**
   * Get systemImage
   * @return systemImage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSystemImage() {
    return systemImage;
  }


  public void setSystemImage(Boolean systemImage) {
    this.systemImage = systemImage;
  }


  public VirtualImage isCloudInit(Boolean isCloudInit) {
    
    this.isCloudInit = isCloudInit;
    return this;
  }

   /**
   * Get isCloudInit
   * @return isCloudInit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsCloudInit() {
    return isCloudInit;
  }


  public void setIsCloudInit(Boolean isCloudInit) {
    this.isCloudInit = isCloudInit;
  }


  public VirtualImage sshUsername(String sshUsername) {
    
    this.sshUsername = sshUsername;
    return this;
  }

   /**
   * Get sshUsername
   * @return sshUsername
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSshUsername() {
    return sshUsername;
  }


  public void setSshUsername(String sshUsername) {
    this.sshUsername = sshUsername;
  }


  public VirtualImage sshPassword(String sshPassword) {
    
    this.sshPassword = sshPassword;
    return this;
  }

   /**
   * Get sshPassword
   * @return sshPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSshPassword() {
    return sshPassword;
  }


  public void setSshPassword(String sshPassword) {
    this.sshPassword = sshPassword;
  }


  public VirtualImage sshPasswordHash(String sshPasswordHash) {
    
    this.sshPasswordHash = sshPasswordHash;
    return this;
  }

   /**
   * Get sshPasswordHash
   * @return sshPasswordHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSshPasswordHash() {
    return sshPasswordHash;
  }


  public void setSshPasswordHash(String sshPasswordHash) {
    this.sshPasswordHash = sshPasswordHash;
  }


  public VirtualImage sshKey(String sshKey) {
    
    this.sshKey = sshKey;
    return this;
  }

   /**
   * Get sshKey
   * @return sshKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSshKey() {
    return sshKey;
  }


  public void setSshKey(String sshKey) {
    this.sshKey = sshKey;
  }


  public VirtualImage osType(VirtualImageOsType osType) {
    
    this.osType = osType;
    return this;
  }

   /**
   * Get osType
   * @return osType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualImageOsType getOsType() {
    return osType;
  }


  public void setOsType(VirtualImageOsType osType) {
    this.osType = osType;
  }


  public VirtualImage minRam(Long minRam) {
    
    this.minRam = minRam;
    return this;
  }

   /**
   * Get minRam
   * @return minRam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getMinRam() {
    return minRam;
  }


  public void setMinRam(Long minRam) {
    this.minRam = minRam;
  }


  public VirtualImage minRamGB(Long minRamGB) {
    
    this.minRamGB = minRamGB;
    return this;
  }

   /**
   * Get minRamGB
   * @return minRamGB
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getMinRamGB() {
    return minRamGB;
  }


  public void setMinRamGB(Long minRamGB) {
    this.minRamGB = minRamGB;
  }


  public VirtualImage minDisk(String minDisk) {
    
    this.minDisk = minDisk;
    return this;
  }

   /**
   * Get minDisk
   * @return minDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMinDisk() {
    return minDisk;
  }


  public void setMinDisk(String minDisk) {
    this.minDisk = minDisk;
  }


  public VirtualImage minDiskGB(String minDiskGB) {
    
    this.minDiskGB = minDiskGB;
    return this;
  }

   /**
   * Get minDiskGB
   * @return minDiskGB
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMinDiskGB() {
    return minDiskGB;
  }


  public void setMinDiskGB(String minDiskGB) {
    this.minDiskGB = minDiskGB;
  }


  public VirtualImage rawSize(Long rawSize) {
    
    this.rawSize = rawSize;
    return this;
  }

   /**
   * Get rawSize
   * @return rawSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getRawSize() {
    return rawSize;
  }


  public void setRawSize(Long rawSize) {
    this.rawSize = rawSize;
  }


  public VirtualImage rawSizeGB(BigDecimal rawSizeGB) {
    
    this.rawSizeGB = rawSizeGB;
    return this;
  }

   /**
   * Get rawSizeGB
   * @return rawSizeGB
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getRawSizeGB() {
    return rawSizeGB;
  }


  public void setRawSizeGB(BigDecimal rawSizeGB) {
    this.rawSizeGB = rawSizeGB;
  }


  public VirtualImage trialVersion(Boolean trialVersion) {
    
    this.trialVersion = trialVersion;
    return this;
  }

   /**
   * Get trialVersion
   * @return trialVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTrialVersion() {
    return trialVersion;
  }


  public void setTrialVersion(Boolean trialVersion) {
    this.trialVersion = trialVersion;
  }


  public VirtualImage virtioSupported(Boolean virtioSupported) {
    
    this.virtioSupported = virtioSupported;
    return this;
  }

   /**
   * Get virtioSupported
   * @return virtioSupported
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getVirtioSupported() {
    return virtioSupported;
  }


  public void setVirtioSupported(Boolean virtioSupported) {
    this.virtioSupported = virtioSupported;
  }


  public VirtualImage uefi(String uefi) {
    
    this.uefi = uefi;
    return this;
  }

   /**
   * Get uefi
   * @return uefi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUefi() {
    return uefi;
  }


  public void setUefi(String uefi) {
    this.uefi = uefi;
  }


  public VirtualImage isAutoJoinDomain(Boolean isAutoJoinDomain) {
    
    this.isAutoJoinDomain = isAutoJoinDomain;
    return this;
  }

   /**
   * Get isAutoJoinDomain
   * @return isAutoJoinDomain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsAutoJoinDomain() {
    return isAutoJoinDomain;
  }


  public void setIsAutoJoinDomain(Boolean isAutoJoinDomain) {
    this.isAutoJoinDomain = isAutoJoinDomain;
  }


  public VirtualImage vmToolsInstalled(Boolean vmToolsInstalled) {
    
    this.vmToolsInstalled = vmToolsInstalled;
    return this;
  }

   /**
   * Get vmToolsInstalled
   * @return vmToolsInstalled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getVmToolsInstalled() {
    return vmToolsInstalled;
  }


  public void setVmToolsInstalled(Boolean vmToolsInstalled) {
    this.vmToolsInstalled = vmToolsInstalled;
  }


  public VirtualImage installAgent(Boolean installAgent) {
    
    this.installAgent = installAgent;
    return this;
  }

   /**
   * Get installAgent
   * @return installAgent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getInstallAgent() {
    return installAgent;
  }


  public void setInstallAgent(Boolean installAgent) {
    this.installAgent = installAgent;
  }


  public VirtualImage isForceCustomization(Boolean isForceCustomization) {
    
    this.isForceCustomization = isForceCustomization;
    return this;
  }

   /**
   * Get isForceCustomization
   * @return isForceCustomization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsForceCustomization() {
    return isForceCustomization;
  }


  public void setIsForceCustomization(Boolean isForceCustomization) {
    this.isForceCustomization = isForceCustomization;
  }


  public VirtualImage isSysprep(Boolean isSysprep) {
    
    this.isSysprep = isSysprep;
    return this;
  }

   /**
   * Get isSysprep
   * @return isSysprep
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsSysprep() {
    return isSysprep;
  }


  public void setIsSysprep(Boolean isSysprep) {
    this.isSysprep = isSysprep;
  }


  public VirtualImage fipsEnabled(Boolean fipsEnabled) {
    
    this.fipsEnabled = fipsEnabled;
    return this;
  }

   /**
   * Get fipsEnabled
   * @return fipsEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getFipsEnabled() {
    return fipsEnabled;
  }


  public void setFipsEnabled(Boolean fipsEnabled) {
    this.fipsEnabled = fipsEnabled;
  }


  public VirtualImage userData(String userData) {
    
    this.userData = userData;
    return this;
  }

   /**
   * Get userData
   * @return userData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserData() {
    return userData;
  }


  public void setUserData(String userData) {
    this.userData = userData;
  }


  public VirtualImage consoleKeymap(String consoleKeymap) {
    
    this.consoleKeymap = consoleKeymap;
    return this;
  }

   /**
   * Get consoleKeymap
   * @return consoleKeymap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConsoleKeymap() {
    return consoleKeymap;
  }


  public void setConsoleKeymap(String consoleKeymap) {
    this.consoleKeymap = consoleKeymap;
  }


  public VirtualImage storageProvider(String storageProvider) {
    
    this.storageProvider = storageProvider;
    return this;
  }

   /**
   * Get storageProvider
   * @return storageProvider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStorageProvider() {
    return storageProvider;
  }


  public void setStorageProvider(String storageProvider) {
    this.storageProvider = storageProvider;
  }


  public VirtualImage externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public VirtualImage visibility(String visibility) {
    
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVisibility() {
    return visibility;
  }


  public void setVisibility(String visibility) {
    this.visibility = visibility;
  }


  public VirtualImage accounts(List<InlineResponse20040AppDeployInstance> accounts) {
    
    this.accounts = accounts;
    return this;
  }

  public VirtualImage addAccountsItem(InlineResponse20040AppDeployInstance accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<InlineResponse20040AppDeployInstance>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Get accounts
   * @return accounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<InlineResponse20040AppDeployInstance> getAccounts() {
    return accounts;
  }


  public void setAccounts(List<InlineResponse20040AppDeployInstance> accounts) {
    this.accounts = accounts;
  }


  public VirtualImage config(VirtualImageConfig config) {
    
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualImageConfig getConfig() {
    return config;
  }


  public void setConfig(VirtualImageConfig config) {
    this.config = config;
  }


  public VirtualImage volumes(List<Object> volumes) {
    
    this.volumes = volumes;
    return this;
  }

  public VirtualImage addVolumesItem(Object volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<Object>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Get volumes
   * @return volumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getVolumes() {
    return volumes;
  }


  public void setVolumes(List<Object> volumes) {
    this.volumes = volumes;
  }


  public VirtualImage storageControllers(List<Object> storageControllers) {
    
    this.storageControllers = storageControllers;
    return this;
  }

  public VirtualImage addStorageControllersItem(Object storageControllersItem) {
    if (this.storageControllers == null) {
      this.storageControllers = new ArrayList<Object>();
    }
    this.storageControllers.add(storageControllersItem);
    return this;
  }

   /**
   * Get storageControllers
   * @return storageControllers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getStorageControllers() {
    return storageControllers;
  }


  public void setStorageControllers(List<Object> storageControllers) {
    this.storageControllers = storageControllers;
  }


  public VirtualImage networkInterfaces(List<Object> networkInterfaces) {
    
    this.networkInterfaces = networkInterfaces;
    return this;
  }

  public VirtualImage addNetworkInterfacesItem(Object networkInterfacesItem) {
    if (this.networkInterfaces == null) {
      this.networkInterfaces = new ArrayList<Object>();
    }
    this.networkInterfaces.add(networkInterfacesItem);
    return this;
  }

   /**
   * Get networkInterfaces
   * @return networkInterfaces
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getNetworkInterfaces() {
    return networkInterfaces;
  }


  public void setNetworkInterfaces(List<Object> networkInterfaces) {
    this.networkInterfaces = networkInterfaces;
  }


  public VirtualImage tags(List<Object> tags) {
    
    this.tags = tags;
    return this;
  }

  public VirtualImage addTagsItem(Object tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Object>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getTags() {
    return tags;
  }


  public void setTags(List<Object> tags) {
    this.tags = tags;
  }


  public VirtualImage locations(List<Object> locations) {
    
    this.locations = locations;
    return this;
  }

  public VirtualImage addLocationsItem(Object locationsItem) {
    if (this.locations == null) {
      this.locations = new ArrayList<Object>();
    }
    this.locations.add(locationsItem);
    return this;
  }

   /**
   * Get locations
   * @return locations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getLocations() {
    return locations;
  }


  public void setLocations(List<Object> locations) {
    this.locations = locations;
  }


  public VirtualImage dateCreated(OffsetDateTime dateCreated) {
    
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }


  public void setDateCreated(OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public VirtualImage lastUpdated(OffsetDateTime lastUpdated) {
    
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }


  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public VirtualImage status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualImage virtualImage = (VirtualImage) o;
    return Objects.equals(this.id, virtualImage.id) &&
        Objects.equals(this.name, virtualImage.name) &&
        Objects.equals(this.description, virtualImage.description) &&
        Objects.equals(this.labels, virtualImage.labels) &&
        Objects.equals(this.ownerId, virtualImage.ownerId) &&
        Objects.equals(this.tenant, virtualImage.tenant) &&
        Objects.equals(this.imageType, virtualImage.imageType) &&
        Objects.equals(this.userUploaded, virtualImage.userUploaded) &&
        Objects.equals(this.userDefined, virtualImage.userDefined) &&
        Objects.equals(this.systemImage, virtualImage.systemImage) &&
        Objects.equals(this.isCloudInit, virtualImage.isCloudInit) &&
        Objects.equals(this.sshUsername, virtualImage.sshUsername) &&
        Objects.equals(this.sshPassword, virtualImage.sshPassword) &&
        Objects.equals(this.sshPasswordHash, virtualImage.sshPasswordHash) &&
        Objects.equals(this.sshKey, virtualImage.sshKey) &&
        Objects.equals(this.osType, virtualImage.osType) &&
        Objects.equals(this.minRam, virtualImage.minRam) &&
        Objects.equals(this.minRamGB, virtualImage.minRamGB) &&
        Objects.equals(this.minDisk, virtualImage.minDisk) &&
        Objects.equals(this.minDiskGB, virtualImage.minDiskGB) &&
        Objects.equals(this.rawSize, virtualImage.rawSize) &&
        Objects.equals(this.rawSizeGB, virtualImage.rawSizeGB) &&
        Objects.equals(this.trialVersion, virtualImage.trialVersion) &&
        Objects.equals(this.virtioSupported, virtualImage.virtioSupported) &&
        Objects.equals(this.uefi, virtualImage.uefi) &&
        Objects.equals(this.isAutoJoinDomain, virtualImage.isAutoJoinDomain) &&
        Objects.equals(this.vmToolsInstalled, virtualImage.vmToolsInstalled) &&
        Objects.equals(this.installAgent, virtualImage.installAgent) &&
        Objects.equals(this.isForceCustomization, virtualImage.isForceCustomization) &&
        Objects.equals(this.isSysprep, virtualImage.isSysprep) &&
        Objects.equals(this.fipsEnabled, virtualImage.fipsEnabled) &&
        Objects.equals(this.userData, virtualImage.userData) &&
        Objects.equals(this.consoleKeymap, virtualImage.consoleKeymap) &&
        Objects.equals(this.storageProvider, virtualImage.storageProvider) &&
        Objects.equals(this.externalId, virtualImage.externalId) &&
        Objects.equals(this.visibility, virtualImage.visibility) &&
        Objects.equals(this.accounts, virtualImage.accounts) &&
        Objects.equals(this.config, virtualImage.config) &&
        Objects.equals(this.volumes, virtualImage.volumes) &&
        Objects.equals(this.storageControllers, virtualImage.storageControllers) &&
        Objects.equals(this.networkInterfaces, virtualImage.networkInterfaces) &&
        Objects.equals(this.tags, virtualImage.tags) &&
        Objects.equals(this.locations, virtualImage.locations) &&
        Objects.equals(this.dateCreated, virtualImage.dateCreated) &&
        Objects.equals(this.lastUpdated, virtualImage.lastUpdated) &&
        Objects.equals(this.status, virtualImage.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, labels, ownerId, tenant, imageType, userUploaded, userDefined, systemImage, isCloudInit, sshUsername, sshPassword, sshPasswordHash, sshKey, osType, minRam, minRamGB, minDisk, minDiskGB, rawSize, rawSizeGB, trialVersion, virtioSupported, uefi, isAutoJoinDomain, vmToolsInstalled, installAgent, isForceCustomization, isSysprep, fipsEnabled, userData, consoleKeymap, storageProvider, externalId, visibility, accounts, config, volumes, storageControllers, networkInterfaces, tags, locations, dateCreated, lastUpdated, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualImage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    imageType: ").append(toIndentedString(imageType)).append("\n");
    sb.append("    userUploaded: ").append(toIndentedString(userUploaded)).append("\n");
    sb.append("    userDefined: ").append(toIndentedString(userDefined)).append("\n");
    sb.append("    systemImage: ").append(toIndentedString(systemImage)).append("\n");
    sb.append("    isCloudInit: ").append(toIndentedString(isCloudInit)).append("\n");
    sb.append("    sshUsername: ").append(toIndentedString(sshUsername)).append("\n");
    sb.append("    sshPassword: ").append(toIndentedString(sshPassword)).append("\n");
    sb.append("    sshPasswordHash: ").append(toIndentedString(sshPasswordHash)).append("\n");
    sb.append("    sshKey: ").append(toIndentedString(sshKey)).append("\n");
    sb.append("    osType: ").append(toIndentedString(osType)).append("\n");
    sb.append("    minRam: ").append(toIndentedString(minRam)).append("\n");
    sb.append("    minRamGB: ").append(toIndentedString(minRamGB)).append("\n");
    sb.append("    minDisk: ").append(toIndentedString(minDisk)).append("\n");
    sb.append("    minDiskGB: ").append(toIndentedString(minDiskGB)).append("\n");
    sb.append("    rawSize: ").append(toIndentedString(rawSize)).append("\n");
    sb.append("    rawSizeGB: ").append(toIndentedString(rawSizeGB)).append("\n");
    sb.append("    trialVersion: ").append(toIndentedString(trialVersion)).append("\n");
    sb.append("    virtioSupported: ").append(toIndentedString(virtioSupported)).append("\n");
    sb.append("    uefi: ").append(toIndentedString(uefi)).append("\n");
    sb.append("    isAutoJoinDomain: ").append(toIndentedString(isAutoJoinDomain)).append("\n");
    sb.append("    vmToolsInstalled: ").append(toIndentedString(vmToolsInstalled)).append("\n");
    sb.append("    installAgent: ").append(toIndentedString(installAgent)).append("\n");
    sb.append("    isForceCustomization: ").append(toIndentedString(isForceCustomization)).append("\n");
    sb.append("    isSysprep: ").append(toIndentedString(isSysprep)).append("\n");
    sb.append("    fipsEnabled: ").append(toIndentedString(fipsEnabled)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    consoleKeymap: ").append(toIndentedString(consoleKeymap)).append("\n");
    sb.append("    storageProvider: ").append(toIndentedString(storageProvider)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("    storageControllers: ").append(toIndentedString(storageControllers)).append("\n");
    sb.append("    networkInterfaces: ").append(toIndentedString(networkInterfaces)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

