package org.openapitools.model;

import groovy.transform.Canonical
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.model.OneOfcredentialAccessSecretKeyConfigcredentialClientIDSecretConfigcredentialEmailPrivateKeyConfigcredentialTenantUsernameKeypairConfigcredentialUsernameAPIKeyConfigcredentialUsernameKeypairConfigcredentialUsernamePasswordConfigcredentialUsernamePasswordKeypairConfigcredentialOauth2Config;

@Canonical
class InlineObject65 {
    /* Payload for updating a credential */
    OneOfcredentialAccessSecretKeyConfigcredentialClientIDSecretConfigcredentialEmailPrivateKeyConfigcredentialTenantUsernameKeypairConfigcredentialUsernameAPIKeyConfigcredentialUsernameKeypairConfigcredentialUsernamePasswordConfigcredentialUsernamePasswordKeypairConfigcredentialOauth2Config credential
}
