package org.openapitools.model;

import groovy.transform.Canonical
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.model.OneOfcredentialAccessSecretKeyConfigcredentialClientIDSecretConfigcredentialEmailPrivateKeyConfigcredentialTenantUsernameKeypairConfigcredentialUsernameAPIKeyConfigcredentialUsernameKeypairConfigcredentialUsernamePasswordConfigcredentialUsernamePasswordKeypairConfigcredentialOauth2Config;

@Canonical
class InlineObject64 {
    /* Payload for creating a new credential */
    OneOfcredentialAccessSecretKeyConfigcredentialClientIDSecretConfigcredentialEmailPrivateKeyConfigcredentialTenantUsernameKeypairConfigcredentialUsernameAPIKeyConfigcredentialUsernameKeypairConfigcredentialUsernamePasswordConfigcredentialUsernamePasswordKeypairConfigcredentialOauth2Config credential
}
