#
# Morpheus API
# Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
# Version: 6.2.1
# Contact: dev@morpheusdata.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'GetNetworkFirewallRules200ResponseAllOfRulesInnerSourcesInner' {
    Context 'GetNetworkFirewallRules200ResponseAllOfRulesInnerSourcesInner' {
        It 'Initialize-GetNetworkFirewallRules200ResponseAllOfRulesInnerSourcesInner' {
            # a simple test to create an object
            #$NewObject = Initialize-GetNetworkFirewallRules200ResponseAllOfRulesInnerSourcesInner -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType GetNetworkFirewallRules200ResponseAllOfRulesInnerSourcesInner
            #$NewObject.property | Should -Be 0
        }
    }
}
