/*
 * Morpheus API
 *
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * API version: 6.2.1
 * Contact: dev@morpheusdata.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse200154 struct for InlineResponse200154
type InlineResponse200154 struct {
	Subnet *Subnet `json:"subnet,omitempty"`
}

// NewInlineResponse200154 instantiates a new InlineResponse200154 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200154() *InlineResponse200154 {
	this := InlineResponse200154{}
	return &this
}

// NewInlineResponse200154WithDefaults instantiates a new InlineResponse200154 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200154WithDefaults() *InlineResponse200154 {
	this := InlineResponse200154{}
	return &this
}

// GetSubnet returns the Subnet field value if set, zero value otherwise.
func (o *InlineResponse200154) GetSubnet() Subnet {
	if o == nil || o.Subnet == nil {
		var ret Subnet
		return ret
	}
	return *o.Subnet
}

// GetSubnetOk returns a tuple with the Subnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200154) GetSubnetOk() (*Subnet, bool) {
	if o == nil || o.Subnet == nil {
		return nil, false
	}
	return o.Subnet, true
}

// HasSubnet returns a boolean if a field has been set.
func (o *InlineResponse200154) HasSubnet() bool {
	if o != nil && o.Subnet != nil {
		return true
	}

	return false
}

// SetSubnet gets a reference to the given Subnet and assigns it to the Subnet field.
func (o *InlineResponse200154) SetSubnet(v Subnet) {
	o.Subnet = &v
}

func (o InlineResponse200154) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Subnet != nil {
		toSerialize["subnet"] = o.Subnet
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200154 struct {
	value *InlineResponse200154
	isSet bool
}

func (v NullableInlineResponse200154) Get() *InlineResponse200154 {
	return v.value
}

func (v *NullableInlineResponse200154) Set(val *InlineResponse200154) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200154) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200154) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200154(val *InlineResponse200154) *NullableInlineResponse200154 {
	return &NullableInlineResponse200154{value: val, isSet: true}
}

func (v NullableInlineResponse200154) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200154) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


