/*
 * Morpheus API
 * Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.
 *
 * The version of the OpenAPI document: 6.2.1
 * Contact: dev@morpheusdata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DashboardBackupsAccountStatsLastSevenDays
 */
public class DashboardBackupsAccountStatsLastSevenDaysTest {
    private final DashboardBackupsAccountStatsLastSevenDays model = new DashboardBackupsAccountStatsLastSevenDays();

    /**
     * Model tests for DashboardBackupsAccountStatsLastSevenDays
     */
    @Test
    public void testDashboardBackupsAccountStatsLastSevenDays() {
        // TODO: test DashboardBackupsAccountStatsLastSevenDays
    }

    /**
     * Test the property 'failed'
     */
    @Test
    public void failedTest() {
        // TODO: test failed
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'completed'
     */
    @Test
    public void completedTest() {
        // TODO: test completed
    }

}
